### ISSUE TITLE
Display grid

### ISSUE THREAD

**Issue by shawal-mbalire** [shawal-mbalire/shawalmbalire.com#2]
change all display flex, flex direction column elements to use dispay grid. and practice how to use display grid. 
also use second parameter ie
```css
*{
display: inline flex;
display: block grid;
display: contents
}
```
